version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es-instance1
    volumes:
      - es_data:/usr/share/elasticsearch/data
      #- ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - ${ES_PORT}:9200
    environment:
      - xpack.security.enabled=false
      #- xpack.security.enrollment.enabled=true
      - discovery.type=single-node
      - node.name=es-instance1
      - cluster.name=es-cluster
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kb-instance1
    volumes:
      - kb_data:/usr/share/kibana/data
      #- ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${ES_USERNAME}
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    networks:
      - elastic

volumes:
  es_data:
    driver: local
  kb_data:
    driver: local

networks:
  elastic:
    driver: bridge