version: '3'

services:
#  nginx:
#    build: infra/nginx
#    ports:
#      - "3000:3000"
  database:
    image: postgres:14.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: smart_qa
      POSTGRES_USER: qa_user
      POSTGRES_PASSWORD: p@ssword
  app:
    build: ./
    ports:
      - "3001:3001"
      - "8000:8000"
    depends_on:
      - database
